// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN5L4o0Y7ZioDF3OYjuZhrPe7K6ZReIMM',
    appId: '1:297923978630:web:8a7660f4c86a9f3666b807',
    messagingSenderId: '297923978630',
    projectId: 'oikonomos-84b69',
    authDomain: 'oikonomos-84b69.firebaseapp.com',
    storageBucket: 'oikonomos-84b69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYgMaTDD1sZg14708NPF7dhFKiZSFePwg',
    appId: '1:297923978630:android:f59ebb717819554266b807',
    messagingSenderId: '297923978630',
    projectId: 'oikonomos-84b69',
    storageBucket: 'oikonomos-84b69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-OfKjTjvORjRavaBI8souO4E0IychE2Q',
    appId: '1:297923978630:ios:4763eedfb5e52dfc66b807',
    messagingSenderId: '297923978630',
    projectId: 'oikonomos-84b69',
    storageBucket: 'oikonomos-84b69.firebasestorage.app',
    iosClientId: '297923978630-0vg2mkr1g0ubfqjjq43a5q0jdmvkt6lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.oikonomos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-OfKjTjvORjRavaBI8souO4E0IychE2Q',
    appId: '1:297923978630:ios:4763eedfb5e52dfc66b807',
    messagingSenderId: '297923978630',
    projectId: 'oikonomos-84b69',
    storageBucket: 'oikonomos-84b69.firebasestorage.app',
    iosClientId: '297923978630-0vg2mkr1g0ubfqjjq43a5q0jdmvkt6lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.oikonomos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN5L4o0Y7ZioDF3OYjuZhrPe7K6ZReIMM',
    appId: '1:297923978630:web:becf62b255972e6266b807',
    messagingSenderId: '297923978630',
    projectId: 'oikonomos-84b69',
    authDomain: 'oikonomos-84b69.firebaseapp.com',
    storageBucket: 'oikonomos-84b69.firebasestorage.app',
  );

}