import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_options.dart'; // This file was generated by the CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // 1. Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text("Firebase Test")),
        // 2. Read Data in Real-time
        body: StreamBuilder(
          stream: FirebaseFirestore.instance.collection('users').snapshots(),
          builder: (context, snapshot) {
            if (!snapshot.hasData) return const Center(child: CircularProgressIndicator());
            
            return ListView(
              children: snapshot.data!.docs.map((doc) {
                return ListTile(
                  title: Text(doc['name'] ?? 'No Name'),
                  subtitle: Text(doc['role'] ?? 'No Role'),
                );
              }).toList(),
            );
          },
        ),
        // 3. Write Data
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            FirebaseFirestore.instance.collection('users').add({
              'name': 'New User',
              'role': 'Developer',
              'timestamp': FieldValue.serverTimestamp(),
            });
          },
          child: const Icon(Icons.shopping_cart),
        ),
      ),
    );
  }
}